FROM oven/bun:1.3.1-alpine AS base

WORKDIR /app

COPY package.json bun.lock ./
COPY turbo.json ./

COPY packages/redis-stream ./packages/redis-stream

COPY apps/cron-worker ./apps/cron-worker

RUN bun install

WORKDIR /app/apps/cron-worker

CMD ["bun", "run", "start:cron-worker"]
