FROM oven/bun:1.3.1 AS base
RUN apt-get update -y && apt-get install -y openssl
WORKDIR /app

FROM base AS deps
COPY package.json bun.lock ./

COPY apps/web2/package.json ./apps/web2/
COPY packages/db ./packages/db

RUN bun install

FROM deps AS builder
WORKDIR /app
COPY . .
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
RUN bun run build --filter=web2

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN groupadd -r -g 1001 nodejs
RUN useradd -r -g nodejs -u 1001 nextjs

COPY --from=builder /app/apps/web2/public ./apps/web2/public
COPY --from=builder --chown=nextjs:nodejs /app/apps/web2/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/web2/.next/static ./apps/web2/.next/static

USER nextjs

EXPOSE 3000

CMD ["bun", "apps/web2/server.js"]