FROM oven/bun:1.3.1-alpine AS base

WORKDIR /app

COPY package.json bun.lock ./
COPY turbo.json ./


COPY packages/db ./packages/db
COPY packages/redis-stream ./packages/redis-stream
COPY apps/evaluator ./apps/evaluator

COPY apps/worker ./apps/worker

RUN bun install 

WORKDIR /app/packages/db
RUN bunx prisma generate

WORKDIR /app/apps/worker

CMD ["bun", "run", "start:worker"]