FROM oven/bun:1.3.1 AS base
RUN apt-get update -y && apt-get install -y openssl
WORKDIR /usr/src/app

FROM base AS install
RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
COPY apps/api/package.json /temp/prod/apps/api/
COPY packages/common/package.json /temp/prod/packages/common/
COPY packages/db/package.json /temp/prod/packages/db/
COPY packages/redis-stream/package.json /temp/prod/packages/redis-stream/

RUN cd /temp/prod && bun install

FROM base AS prerelease
COPY --from=install /temp/prod/node_modules node_modules
COPY . .

RUN cd packages/db && bunx prisma generate

FROM oven/bun:1.3.1-slim AS release
RUN apt-get update -y && apt-get install -y openssl
WORKDIR /usr/src/app

ENV NODE_ENV=production

COPY --from=prerelease /usr/src/app/node_modules ./node_modules
COPY --from=prerelease /usr/src/app/apps/api ./apps/api
COPY --from=prerelease /usr/src/app/packages ./packages
COPY --from=prerelease /usr/src/app/package.json ./

USER bun

EXPOSE 4000/tcp

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD bun --version || exit 1

ENTRYPOINT [ "bun", "run", "--cwd", "apps/api", "start:backend" ]
