FROM oven/bun:1.3.1-alpine AS base

WORKDIR /app

COPY package.json bun.lock ./
COPY turbo.json ./

COPY packages/redis-stream ./packages/redis-stream
COPY packages/db ./packages/db

COPY apps/evaluator /apps/evaluator

RUN bun install

WORKDIR /app/packages/db
RUN bunx prisma generate

WORKDIR /app/apps/evaluator