FROM oven/bun:1.3.1-alpine AS base

WORKDIR /app

COPY package.json bun.lock ./
COPY turbo.json ./

COPY packages/redis-stream ./packages/redis-stream

COPY apps/leaderboard-worker /apps/leaderboard-worker

RUN bun install

WORKDIR /app/apps/leaderboard-worker

EXPOSE 8080

CMD ["bun", "run" ,"start:leaderboard"]