FROM oven/bun:1.3.1-alpine AS base
WORKDIR /app

FROM base AS deps
# Copy root package.json and lockfile
COPY package.json bun.lock ./

COPY apps/web2/package.json ./apps/web2/
COPY packages/db ./packages/db

RUN bun install

FROM deps AS builder
WORKDIR /app
COPY . .
RUN bun run build --filter=web2

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/apps/web2/public ./apps/web2/public
COPY --from=builder --chown=nextjs:nodejs /app/apps/web2/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/web2/.next/static ./apps/web2/.next/static

USER nextjs

EXPOSE 3000

CMD ["bun", "apps/web2/server.js"]