FROM oven/bun:1.3.1-alpine AS base

WORKDIR /app

COPY package.json bun.lock ./
COPY turbo.json ./

COPY packages/redis-stream ./packages/redis-stream

COPY apps/realtime /apps/realtime

RUN bun install

WORKDIR /app/apps/realtime

EXPOSE 8080

CMD ["bun", "run" ,"start:realtime"]